### ISSUE TITLE
how can use ApplmaGen to build ibus input framework

### ISSUE THREAD

**Issue by newyorkthink** [ivan-hc/AppImaGen#1]
![image](https://github.com/ivan-hc/AppImaGen/assets/87791643/062965d3-7384-484d-bd70-4d006994dd04)
![image](https://github.com/ivan-hc/AppImaGen/assets/87791643/fecf8e59-d475-484f-b7d3-8f17044090f0)

**Comment by newyorkthink** [comment]
i dont not how build

**Comment by ivan-hc** [comment]
it's a bit difficult with AppImagen, you require also an icon and a launcher

use https://github.com/ivan-hc/ArchImage instead, download https://github.com/ivan-hc/ArchImage/blob/main/sample-junest.sh and change the values by following the guide lines into it

PS: the error message is about the missing path where the ibus binary is installed (normally it is `/usr/bin/ibus`)
